
services:
  mysql-test-nest:
    image: mysql:8.0
    container_name: container-mysql-test-nest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: P@sser123
    ports:
      - 3308:3306
    volumes:
      - mysql_data_test-nest_2:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD

  phpmyadmin-test-nest:
    container_name: phpmyadmin-test-nest
    image: phpmyadmin/phpmyadmin
    ports:
      - 8088:80
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql-test-nest
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql-test-nest
    restart: unless-stopped

volumes:
  mysql_data_test-nest_2:
    driver: local
